Ecommercial/shoppage/basic_app/urls.py
from basic_app import views
from django.conf.urls import url

app_name = 'basic_app'

urlpatterns = [
    url(r'base/$',views.base),
    url(r'index/$',views.index,name = 'index'),
    url(r'about/$',views.about,name = 'about'),
    url(r'contact/$',views.contact,name = 'contact'),
    url(r'products/$',views.products,name = 'products'),
    url(r'login/$',views.login,name = 'login'),
    url(r'faqs/$',views.faqs,name = 'faqs'),
    url(r'preview/$',views.preview,name = 'preview'),
    url(r'cart/$',views.cart,name = 'cart'),

]

Ecommercial/shoppage/shoppage/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls'))

]

Ecommercial/shoppage/basic_app/models.py
from django.db import models

# Create your models here.

Ecommercial/shoppage/basic_app/views.py
from django.shortcuts import render
from basic_app import views

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')
def base(request):
    return render(request,'basic_app/base.html')
def about(request):
    return render(request,'basic_app/about.html')
def contact(request):
    return render(request,'basic_app/contact.html')
def products(request):
    return render(request,'basic_app/products.html')
def login(request):
    return render(request,'basic_app/login.html')
def faqs(request):
    return render(request,'basic_app/faq.html')
def preview(request):
    return render(request,'basic_app/preview.html')
def cart(request):
    return render(request,'basic_app/shopping_cart.html')

Ecommercial/shoppage/templates/basic_app/about.html
{% extends "basic_app/base.html" %}
  {% load static %}
  {% block body_block %}
     <div class="main">
        <div class="content">
        	<div class="section group">
    				<div class="col_1_of_3 span_1_of_3">
    					<h3>Who We Are</h3>
    					<img src=" {% static "images/about-img.jpg" %} " alt="" />
    					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    				</div>
    				<div class="col_1_of_3 span_1_of_3">
    					<h3>Our History</h3>
    				 <div class="history-desc">
    					<div class="year"><p>1998 -</p></div>
    					<p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    				 <div class="clear"></div>
    				</div>
    				 <div class="history-desc">
    					<div class="year"><p>2001 -</p></div>
    					<p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</p>
    				 <div class="clear"></div>
    				</div>
    				 <div class="history-desc">
    					<div class="year"><p>2006 -</p></div>
    					<p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    				 <div class="clear"></div>
    				</div>
    				 <div class="history-desc">
    					<div class="year"><p>2010 -</p></div>
    					<p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    				 <div class="clear"></div>
    				</div>
    				<div class="history-desc">
    					<div class="year"><p>2013 -</p></div>
    					<p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</p>
    				 <div class="clear"></div>
    				</div>
    			</div>
    				<div class="col_1_of_3 span_1_of_3">
    					<h3>Opportunities</h3>
    					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    				    <div class="list">
    					     <ul>
    					     	<li><a href="#">Text of the printing</a></li>
    					     	<li><a href="#">Lorem Ipsum has been the standard</a></li>
    					     	<li><a href="#">Dummy text ever since the 1500s</a></li>
    					     	<li><a href="#">Unknown printer took a galley</a></li>
    					     	<li><a href="#">Led it to make a type specimen</a></li>
    					     	<li><a href="#">Not only five centuries</a></li>
    					     	<li><a href="#">Electronic typesetting</a></li>
    					     	<li><a href="#">Unchanged. It was popularised</a></li>
    					     	<li><a href="#">Sheets containing Lorem Ipsume</a></li>
    					     </ul>
    					 </div>
    					 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    				</div>
    			</div>
    			<h2>OUR TEAM</h2>
    			<div class="section group">
    				<div class="grid_1_of_5 images_1_of_5">
    					 <img src=" {% static "images/team1.jpg" %} " alt="" />
    					  <h3>Lorem Ipsum is simply </h3>
    					 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    				</div>
    				<div class="grid_1_of_5 images_1_of_5">
    					  <img src=" {% static "images/team2.jpg" %} " alt="" />
    					  <h3>Lorem Ipsum is simply </h3>
    					 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    				</div>
    				<div class="grid_1_of_5 images_1_of_5">
    					  <img src=" {% static "images/team3.jpg" %} " alt="" />
    					 <h3>Lorem Ipsum is simply </h3>
    					 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    				</div>
    				<div class="grid_1_of_5 images_1_of_5">
    					  <img src=" {% static "images/team4.jpg" %} " alt="" />
    					 <h3>Lorem Ipsum is simply </h3>
    					 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    				</div>
    				<div class="grid_1_of_5 images_1_of_5">
    					  <img src=" {% static "images/team2.jpg" %} " alt="" />
    					  <h3>Lorem Ipsum is simply </h3>
    					 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    				</div>
    			</div>
        	<div>
        </div>
     </div>
    </div>

  {% endblock %}

Ecommercial/shoppage/templates/basic_app/base.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
<title>Free Smart Store Website Template | Home :: w3layouts</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href= "{% static "css/style.css" %}" rel="stylesheet" type="text/css" media="all"/>
<link href= "{% static "css/menu.css" %}" rel="stylesheet" type="text/css" media="all"/>
<script src=" {% static "js/jquery.min.js" %}"></script>
<script src=" {% static "js/script.js" %}" type="text/javascript"></script>
<script type="text/javascript" src=" {% static "js/move-top.js" %}"></script>
<script type="text/javascript" src=" {% static "js/easing.js" %}"></script>
<link href='//fonts.googleapis.com/css?family=Monda' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Doppio+One' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="wrap">
	<div class="header">
		<div class="header_top">
			<div class="logo">
				<a href="index.html"><img src=" {% static "images/logo.png" %} " alt="" /></a>
			</div>
			  <div class="header_top_right">
			    <div class="search_box">
				    <form>
				    	<input type="text" value="Search for Products" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search for Products';}"><input type="submit" value="SEARCH">
				    </form>
			    </div>
			    <div class="shopping_cart">
					<div class="cart">
						<a href="{% url "basic_app:cart" %}" title="View my shopping cart" rel="nofollow">
							<strong class="opencart"> </strong>
								<span class="cart_title">Cart</span>
									<span class="no_product">(empty)</span>
							</a>
						</div>
			      </div>
	    <div class="languages" title="language">
	    	<div id="language" class="wrapper-dropdown" tabindex="1">EN
						<strong class="opencart"> </strong>
						<ul class="dropdown languges">
							 <li>
							 	<a href="#" title="Français">
									<span><img src=" {% static "images/gb.png" %} " alt="en" width="26" height="26"></span><span class="lang">English</span>
								</a>
							 </li>
								<li>
									<a href="#" title="Français">
										<span><img src=" {% static "images/au.png" %} " alt="fr" width="26" height="26"></span><span class="lang">Français</span>
									</a>
								</li>
						<li>
							<a href="#" title="Español">
								<span><img src=" {% static "images/bm.png" %} " alt="es" width="26" height="26"></span><span class="lang">Español</span>
							</a>
						</li>
								<li>
									<a href="#" title="Deutsch">
										<span><img src=" {% static "images/ck.png" %} " alt="de" width="26" height="26"></span><span class="lang">Deutsch</span>
									</a>
								</li>
						<li>
							<a href="#" title=" russian">
								<span><img src=" {% static "images/cu.png" %} " alt=" ru" width="26" height="26"></span><span class="lang">Russian</span>
							</a>
						</li>
				   </ul>
		     </div>
		     <script type="text/javascript">
			function DropDown(el) {
				this.dd = el;
				this.initEvents();
			}
			DropDown.prototype = {
				initEvents : function() {
					var obj = this;

					obj.dd.on('click', function(event){
						$(this).toggleClass('active');
						event.stopPropagation();
					});
				}
			}

			$(function() {

				var dd = new DropDown( $('#language') );

				$(document).click(function() {
					// all dropdowns
					$('.wrapper-dropdown').removeClass('active');
				});

			});

		</script>
		 </div>
			<div class="currency" title="currency">
					<div id="currency" class="wrapper-dropdown" tabindex="1">$
						<strong class="opencart"> </strong>
						<ul class="dropdown">
							<li><a href="#"><span>$</span>Dollar</a></li>
							<li><a href="#"><span>€</span>Euro</a></li>
						</ul>
					</div>
					 <script type="text/javascript">
			function DropDown(el) {
				this.dd = el;
				this.initEvents();
			}
			DropDown.prototype = {
				initEvents : function() {
					var obj = this;

					obj.dd.on('click', function(event){
						$(this).toggleClass('active');
						event.stopPropagation();
					});
				}
			}

			$(function() {

				var dd = new DropDown( $('#currency') );

				$(document).click(function() {
					// all dropdowns
					$('.wrapper-dropdown').removeClass('active');
				});

			});

		</script>
   </div>
		   <div class="login">
		   	   <span><a href="{% url "basic_app:login" %}"><img src=" {% static "images/login.png" %} " alt="" title="login"/></a></span>
		   </div>
		 <div class="clear"></div>
	 </div>
	 <div class="clear"></div>
 </div>
	<div class="h_menu">
		<a id="touch-menu" class="mobile-menu" href="#">Menu</a>
		<nav>
		<ul class="menu list-unstyled">
			<li><a href="{% url "basic_app:index" %}">HOME</a></li>
			<li class="activate"><a href="{% url "basic_app:products" %}">Products</a>
				<ul class="sub-menu list-unstyled">
				 <div class="nag-mother-list">
				   <div class="navg-drop-main">
					<div class="nav-drop">
						<li><a href="products.html">Product 1</a></li>
						<li><a href="products.html">Product 2</a></li>
						<li><a href="products.html">Product 3</a>
						</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 1</a></li>
						<li><a href="products.html">Product 2</a></li>
						<li><a href="products.html">Product 3</a>
								</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 1</a></li>
						<li><a href="products.html">Product 2</a></li>
						<li><a href="products.html">Product 3</a></li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 1</a></li>
						<li><a href="products.html">Product 2</a></li>
						<li><a href="products.html">Product 3</a></li>
					</div>
					<div class="clear"> </div>
				</div>
				<div class="navg-drop-main">
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a>

						</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a>
								</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a></li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a></li>
					</div>
					<div class="clear"> </div>
				 </div>
				 <div class="navg-drop-main">
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a>

						</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a>
								</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a></li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a></li>
					</div>
					<div class="clear"> </div>
				 </div>
				</div>
			</ul></li>
			<li><a href="{% url "basic_app:products" %}">Top Brand</a>
				<ul class="sub-menu list-unstyled sub-menu2">
				  <div class="navg-drop-main">
						<div class="nav-drop nav-top-brand">
							<li><a href="products.html">Product 1</a></li>
							<li><a href="products.html">Product 2</a></li>
							<li><a href="products.html">Product 3</a></li>
							<li><a href="products.html">Product 4</a></li>
						   <li><a href="products.html">Product 5</a></li>
						   <li><a href="products.html">Product 6</a></li>
						</div>
					</div>
				</ul></li>
			<li><a href="{% url "basic_app:faqs" %}">Services</a>
				<ul class="sub-menu list-unstyled sub-menu3">
				  <div class="navg-drop-main">
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a>

						</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a>
								</li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a></li>
					</div>
					<div class="nav-drop">
						<li><a href="products.html">Product 4</a></li>
						<li><a href="products.html">Product 5</a></li>
						<li><a href="products.html">Product 6</a></li>
					</div>
					<div class="clear"> </div>
				 </div>
			  </ul></li>
			<li><a href="{% url "basic_app:about" %}">About</a></li>
			<li><a href="{% url "basic_app:contact" %}">Delivery</a></li>
			<li><a href="{% url "basic_app:faqs" %}">Faqs</a></li>
			<li><a href="{% url "basic_app:contact" %}">CONTACT</a></li>
			<div class="clear"> </div>
		</ul>
		</nav>
		<script src=" {% static "js/menu.js" %}" type="text/javascript"></script>
		</div>




    {%block body_block%}
      <!-- nothing here -->

    {% endblock %}















   <div class="footer">
   	  <div class="wrapper">
	     <div class="section group">
				<div class="col_1_of_4 span_1_of_4">
						<h4>Information</h4>
						<ul>
						<li><a href="{% url "basic_app:about" %}">About Us</a></li>
						<li><a href="#">Customer Service</a></li>
						<li><a href="#"><span>Advanced Search</span></a></li>
						<li><a href="#">Orders and Returns</a></li>
						<li><a href="#"><span>Contact Us</span></a></li>
						</ul>
					</div>
				<div class="col_1_of_4 span_1_of_4">
					<h4>Why buy from us</h4>
						<ul>
						<li><a href="{% url "basic_app:about" %}">About Us</a></li>
						<li><a href="faq.html">Customer Service</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="contact.html"><span>Site Map</span></a></li>
						<li><a href="preview-2.html"><span>Search Terms</span></a></li>
						</ul>
				</div>
				<div class="col_1_of_4 span_1_of_4">
					<h4>My account</h4>
						<ul>
							<li><a href="{% url "basic_app:login" %}">Sign In</a></li>
							<li><a href="{% url "index" %}">View Cart</a></li>
							<li><a href="{% url "index" %}">My Wishlist</a></li>
							<li><a href="{% url "index" %}">Track My Order</a></li>
							<li><a href="{% url "basic_app:contact" %}"Help</a></li>
						</ul>
				</div>
				<div class="col_1_of_4 span_1_of_4">
					<h4>Contact</h4>
						<ul>
							<li><span>+91-123-456789</span></li>
							<li><span>+00-123-000000</span></li>
						</ul>
						<div class="social-icons">
							<h4>Follow Us</h4>
					   		  <ul>
							      <li class="facebook"><a href="https://www.facebook.com/" target="_blank"> </a></li>
							      <li class="twitter"><a href="https://www.twitter.com/" target="_blank"> </a></li>
							      <li class="googleplus"><a href="https://www.googleplus.com/" target="_blank"> </a></li>
							      <li class="contact"><a href="{% url "basic_app:contact" %}" target="_blank"> </a></li>
							      <div class="clear"></div>
						     </ul>
   	 					</div>
				</div>
			</div>
			<div class="copy_right">
				<p>&copy; 2013 Smart Store. All Rights Reserved | Design by <a href="http://w3layouts.com">W3Layouts</a> </p>
		   </div>
     </div>
    </div>
    <script type="text/javascript">
		$(document).ready(function() {
			/*
			var defaults = {
	  			containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
	 		};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

		});
	</script>
    <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
    <link href= "{% static "css/flexslider.css" %}" rel='stylesheet' type='text/css' />
							  <script defer src=" {% static "js/jquery.flexslider.js" %}"></script>
							  <script type="text/javascript">
								$(function(){
								  SyntaxHighlighter.all();
								});
								$(window).load(function(){
								  $('.flexslider').flexslider({
									animation: "slide",
									start: function(slider){
									  $('body').removeClass('loading');
									}
								  });
								});
							  </script>
</body>
</html>

Ecommercial/shoppage/templates/basic_app/contact.html
{% extends "basic_app/base.html" %}
  {% load static %}
  {% block body_block %}
       <div class="main">
          <div class="content">
          	<div class="support">
        			<div class="support_desc">
        				<h3>Live Support</h3>
        				<p><span>24 hours | 7 days a week | 365 days a year &nbsp;&nbsp; Live Technical Support</span></p>
        				<p> It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>
        			</div>
        				<img src=" {%  static "images/contact.png" %}" alt="" />
        			<div class="clear"></div>
        		</div>
          	<div class="section group">
      				<div class="col span_2_of_3">
      				  <div class="contact-form">
      				  	<h2>Contact Us</h2>
      					    <form>
      					    	<div>
      						    	<span><label>NAME</label></span>
      						    	<span><input type="text" value=""></span>
      						    </div>
      						    <div>
      						    	<span><label>E-MAIL</label></span>
      						    	<span><input type="text" value=""></span>
      						    </div>
      						    <div>
      						     	<span><label>MOBILE.NO</label></span>
      						    	<span><input type="text" value=""></span>
      						    </div>
      						    <div>
      						    	<span><label>SUBJECT</label></span>
      						    	<span><textarea> </textarea></span>
      						    </div>
      						   <div>
      						   		<span><input type="submit" value="SUBMIT"></span>
      						  </div>
      					    </form>
      				  </div>
        				</div>
      				<div class="col span_1_of_3">
      					<div class="contact_info">
          	 				<h2>Find Us Here</h2>
      					    	  <div class="map">
      							   	    <iframe width="100%" height="175" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265&amp;output=embed"></iframe><br><small><a href="https://maps.google.co.in/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265" style="color:#666;text-align:left;font-size:12px">View Larger Map</a></small>
      							  </div>
            				</div>
            			<div class="company_address">
      				     	<h2>Company Information :</h2>
      						    	<p>500 Lorem Ipsum Dolor Sit,</p>
      						   		<p>22-56-2-9 Sit Amet, Lorem,</p>
      						   		<p>USA</p>
      				   		<p>Phone:(00) 222 666 444</p>
      				   		<p>Fax: (000) 000 00 00 0</p>
      				 	 	<p>Email: <span><a href="mailto:info@mycompany.com">info@mycompany.com</a></span></p>
      				   		<p>Follow on: <span><a href="#">Facebook</a></span>, <span><a href="#">Twitter</a></span></p>
      				   </div>
      				 </div>
      			  </div>
          </div>
       </div>
   {% endblock %}