Level_4_templates/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE NAME
app_name = 'basic_app'


urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^other/$',views.other,name='other'),
    url(r'^relative/$',views.relative,name='relative'),
]

Level_4_templates/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url('admin/', admin.site.urls),
    url(r'basic_app/',include('basic_app.urls')),

]

Level_4_templates/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Level_4_templates/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')
    
def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

Level_4_templates/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'basic_app:relative' %}">RELATIVE</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'basic_app:other'%}">OTHER</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index'%}">ADMIN.DB</a>
          </li>
        </ul>
      </div>
    </nav>

      <div class="container">
        {% block body_block %}
          <!-- skip anything in block to insert NEW, e.g: from index.html,other.html -->
        {% endblock%}
      </div>

  </body>
</html>

Level_4_templates/learning_templates/templates/basic_app/index.html
{% extends 'basic_app/base.html'%}
<!DOCTYPE html>
{% block body_block%}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index_style.css'%}">
    <h1 class="d-flex justify-content-center">Welcome to INDEX</h1>
    <div class="col-12"> <img src="{% static "images/jpg.jpg" %}" alt=""></div>
    <div class="">
      {{text | upper}}
      {{text | cut:'hello' | upper}}
      {{number | add:'899'}}
    </div>

{% endblock%}

Level_4_templates/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/other_style.css'%}">
      <h1 class="d-flex justify-content-center" >Welcome to OTHER</h1>
      <ul>
        <li>
          <a href="{% url 'basic_app:relative' %}">link to RELATIVE</a>
        </li>
        <li><a href="{% url 'index' %}">link to ADMIN</a></li>
        <li> <a href="{% url 'basic_app:index'%}"> link to INDEX</a></li>
      </ul>
{% endblock %}

Level_4_templates/learning_templates/templates/basic_app/relative_url_templates.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/relative_style.css'%}">
    <h1 class="d-flex justify-content-center" >Welcome to RELATIVE page</h1>
    <ul>
      <li>
        <a href="{% url 'basic_app:other' %}">link to OTHER</a>
      </li>
      <li><a href="{% url 'admin:index' %}">link to ADMIN</a></li>
      <li> <a href="{% url 'basic_app:index'%}"> link to INDEX</a></li>
      <div class="">
        RELATIVE : ipsum dolor sit amet, consectetur
        adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua. Ut enim ad minim veniam, quis nostrud exercit
      </div>
    </ul>
{% endblock %}