zAdvance_section/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$',views.index,name='index')
    # url(r'^$',views.CBView.as_view()),
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app'))
]

zAdvance_section/advcbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
    url(r'^(?P<pk>\d+)/create/',views.StudentCreateView.as_view(),name='stu_create')


]

zAdvance_section/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})      # why this ?

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    # def get_absolute_url(self):
        # return reverse("basic_app:detail",kwargs={'pk':self.pk})

zAdvance_section/advcbv/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy,reverse
from . import models
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,UpdateView,
                                DeleteView)


def url(request):
    uri = request.build_absolute_uri()
    url = request.build_absolute_uri('?')
    print(uri)
    print(url)

# def index(request):
#     return render(request,'index.html')

# class CBView(View):
#     def get(self,request):
#         return HttpResponse(" USE CBVIEWs ARE COOL!")

class IndexView(TemplateView):
    template_name = 'index.html'
#
#     def get_context_data(self,**kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = 'BASIC INJECTION'
#         return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    # template_name = 'basic_app/school_list.html' # the school_list auto

################ SCHOOL CRUD ################

class SchoolDetailView(DetailView):     # retrieve _ get data
    context_object_name = 'school_detail'
    model = models.School
    # template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

################ SCHOOL CRUD ################

class StudentCreateView(CreateView,View,):
    fields = ('name','age','school')
    model = models.Student
    print('#'*20,'#'*20)
    # print
    #
    # url(request)

    # the rule url(regex=r'^user/(?P<username>\w{1,50})/$', view='views.profile_page')
    # a in incoming request for http://domain/user/thaiyoshi/?message=Hi



    # def profile_page(request, username=None):
    #     user = User.objects.get(username=username)
    #     message = request.GET.get('message')
    #     print(user)
    #     print(message)

    success_url = reverse_lazy('basic_app:list')

zAdvance_section/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url "index" %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "basic_app:list" %}">School <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
      </li>

    </ul>
  </div>
</nav>

    <div class="container">

        {% block body_block%}

        {% endblock%}
     </div>

  </body>
</html>

zAdvance_section/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block%}
  <h1>Delete : {{ school.name }} ?</h1>
  <form class="" action="" method="post">
      {% csrf_token%}
      <input class="btn btn-danger" type="submit" name="" value="Delete">
      <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>

  </form>

{% endblock %}

zAdvance_section/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block%}
{% load static %}
<link rel="stylesheet" href="{% static "css/school_detail_style.css"%}">
  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h3>School details : </h3>
    <p>Name : {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>

    <h3>Student details : </h3>
    {% for student in school_detail.students.all %}
        <p>{{student.name}} : {{student.age}} years old</p>
    {% endfor %}
  </div>

  <div class="container">
    <p class="button-ed"><a class="btn btn-primary" href="{% url "basic_app:update" pk=school_detail.pk %}">Update</a></p>
    <p class="button-ed"><a class = "btn btn-danger" href="{% url "basic_app:delete" pk=school_detail.pk %}">Delete</a></p>
  </div>



{% endblock%}

zAdvance_section/advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block%}

  <div class="jumbotron">
    <h1>
      Welcome to the School creating form
      {% if not form.instance.pk %}
      Create School
      {% else %}
      Update School
      {% endif %}
    </h1>
  </div>
  <form class="" action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-primary" name="" value="Submit ">
  </form>
{% endblock%}

zAdvance_section/advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block %}

<h1> Welcome to the list of all the school!</h1>
  <ol>
    {% for school in schools %}
      <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>
<p><a class="btn btn-primary" href="{% url "basic_app:create" %}">Create</a></p>


{% endblock %}

zAdvance_section/advcbv/basic_app/templates/basic_app/student_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block%}
  <h1>Add new student</h1>
  <form class="" action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-primary" type="submit" name="" value="Add">
  </form>
{% endblock %}

zAdvance_section/advcbv/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url "index" %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "basic_app:list" %}">School <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
      </li>

    </ul>
  </div>
</nav>

    <div class="container">

        {% block body_block%}

        {% endblock%}
     </div>

  </body>
</html>

zAdvance_section/advcbv/templates/index.html
{% extends "base.html"%}


{% block body_block%}
  <!-- <h1>Hello wolrd INDEX</h1>
  <h2>Injected Content: {{ injectme }}</h2> -->
  <div class="jumbotron d-flex justify-content-center ">
    <h1>HOMEPAGE</h1>
  </div>
{%endblock%}