zblog_project/mysite/blog/urls.py
from django.conf.urls import url
from blog import views

app_name ='blog'

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name='remove'),
    url(r'^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_post,name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name= 'comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name= 'comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),
]

zblog_project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views
from django.contrib.auth.mixins import LoginRequiredMixin

urlpatterns = [
    path('^admin/', admin.site.urls),
    url(r'',include("blog.urls")),
    # url(r'accounts/login/$',views.login,name='login'),
    # url(r'accounts/logout/$',views.logout,name='logout',kwargs={'next page':'/'}),
]

zblog_project/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# from django.contrib.auth import User
# Create your models here.

class   Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now())
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def approve_comments(self):
        return self.comments.filter(approve_comment =True)
    def get_absolute_url(self):
        return reverse("post_detail",kwargs={"pk:self"})
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length = 200)
    text= models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    approve_comment  = models.BooleanField(default=False)
    def approve(self):
        self.approve_comment = True
        self.save()
    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

zblog_project/mysite/blog/forms.py
from django import forms
from blog.models import Post,Comment


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author','title','text')
    widgets = {
        'title' : forms.TextInput(attrs={'class':'textinputclass'}),
         'text' : forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
    }

class CommenForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields  = ('author','text')

    widgets = {
        'author' : forms.TextInput(attrs= {'class':'textinputclass'} ),
         'text' : forms.Textarea(attrs={'class':'editable medium-editor-textarea '})
    }

zblog_project/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from django.views.generic import (TemplateView,ListView,
                                DetailView, CreateView,
                                UpdateView, DeleteView,)
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import PostForm,Comment
from django.urls import reverse_lazy
from blog.models import Post,Comment
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.views import LoginView, LogoutView
# Create your views here.

# class login(LoginView):
#     # login_url = '/login/'
#     redirect_field_name = 'blog/post_detail.html'

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = Post

    def get_query(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by("-published_date")
        # SELECT post_tuple WHERE published_date <= timezone.now() ORDER_BY DESC published_date # newest

class  PostDetailView(DetailView):
    model = Post

class CreatePostView(CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.object.filter(published_date__isnull=True).order_by('create_date')

###########################
###########################

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish
    return redirect('post_detail',pk=pk)


@login_required
def add_comment_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect('post_detail',pk=post.pk)
    else:
        form = CommentForm()
        return render(request,'blog/comment_form.html',{'form':form})

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(comment,pk=pk)
    comment.approve()
    return redirect('post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail',pk=post_pk)

zblog_project/mysite/blog/templates/blog/about.html
{% extends "blog/base.html"%}

{% block content %}

  <h1>About this company</h1>
  <p>Thanks for checking it out!</p>

{% endblock%}

zblog_project/mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- medium style editor -->

    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!-- custom CSS -->
    <link rel="stylesheet" href=" {%static "css/style.css" %}">


    <!-- Fonts -->

    <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">



  </head>
  <body>

    <!-- nav-bar -->
      <nav class="navbar navbar-default techfont custom-navbar row">
        <div class="container">

          <ul class="nav navbar-nav col-6" style="float:left !important; width">
            <li class=" " >
              <a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class=" " style="float:left !important">
              <a class="  " href="{% url 'blog:about' %}">About <span class="sr-only">(current)</span></a>
            </li>
            <li class=" ">
              <a class="  " href="https://www.github.com">Github <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="  " href="https://www.LinkedIn.com">LinkedIn</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right" >
            {% if user.is_authenticated %}
              <li class=" "> <a href="{% url 'blog:post_new'%}"> New Post</a> </li>
              <li class=" "> <a href="{% url 'blog:post_new'%}"> Draft</a> </li>
              <li class=" "> <a href="{% url 'login'%}"> Log Out</a> </li>
              <li class=" "> <a > Welcome : {{user.username}}</a> </li>      
            {% endif %}

          </ul>

        </div>

      </nav>
    <!-- content-blog -->

    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_post">
            {% block content%}

            {% endblock%}

          </div>

        </div>

      </div>
    </div>



  </body>
</html>

zblog_project/mysite/blog/templates/blog/base0.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- medium style editor -->

    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!-- custom CSS -->
    <link rel="stylesheet" href=" {%static "css/style.css" %}">


    <!-- Fonts -->

    <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">



  </head>
  <body>

    <!-- nav-bar -->
      <nav class="navbar navbar-default techfont custom-navbar row">
        <div class="container">

          <ul class="nav navbar-nav col-6" style="float:left !important; width">
            <li class=" " >
              <a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class=" " style="float:left !important">
              <a class="  " href="{% url 'blog:about' %}">About <span class="sr-only">(current)</span></a>
            </li>
            <li class=" ">
              <a class="  " href="https://www.github.com">Github <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="  " href="https://www.LinkedIn.com">LinkedIn</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right" >
            {% if user.is_authenticated %}
              <li class=" "> <a href="{% url 'blog:post_new'%}"> New Post</a> </li>
              <li class=" "> <a href="{% url 'blog:post_new'%}"> Draft</a> </li>
              <li class=" "> <a href="{% url 'login'%}"> Log Out</a> </li>
              <li class=" "> <a > Welcome : {{user.username}}</a> </li>
            {% else %}
              <li class=" "> <a class="nav navbar-right" href="{% url 'blog:login' %}"> <span class="glyphicon glyphicon-user"></span> </a> </li>
            {% endif %}

          </ul>

        </div>

      </nav>
    <!-- content-blog -->

    <div class="content container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_post">
            {% block content%}

            {% endblock%}

          </div>

        </div>

      </div>
    </div>



  </body>
</html>

zblog_project/mysite/blog/templates/blog/comment_form.html
{% extends "blog/base.html"%}

{% block content %}

{% endblock%}

zblog_project/mysite/blog/templates/blog/post_confirm.html
{% extends "blog/base.html"%}

{% block content %}
  <h1>New Comment</h1>
  <form class="post-form"  method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" name="" class="save btn btn-default">Post Comment</button>
  </form>
  <script>var editor = new MediumEditor('.editable');</script>
{% endblock%}

zblog_project/mysite/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html"%}

{% block content %}
  <form class="" method="post">
    {% csrf_token %}
    <p> Are you sure you want to delete {{object}} ? </p>
    <input class="btn btn-danger" type="submit" name="delete" value="confirm" >

  </form>
{% endblock%}

zblog_project/mysite/blog/templates/blog/post_detail.html
{% extends "blog/base.html"%}

{% block content %}
  <h1 class="posttitle loader"> {{post.title}} </h1>
  {% if post.published_date%}
      <div class="data postdate">
        {{post.published_date}}
      </div>
  {% else %}
      <a href="{%url 'post_publish' pk=post.pk%}" class="btn btn-default">Publish</a>
  {%endif%}
    <b> bold text </b>
    <p class="postcontent">{{post.title|safe|linebreaks}}</p>
  {% if user.is_authenticated %}
    <a class="button btn-primary" href="{% url 'post_edit' pk=post.pk  %}">
      <span class="glyphicon glymphicon-pencil"></span>
    </a>
    <a class="button btn-primary" href="{% url 'post_remove' pk=post.pk  %}">
      <span class="glyphicon glymphicon-remove"></span>
    </a>
  {% endif %}
  <hr>
    <a href="{% url 'add_comment_to_post' pk=post.pk %}" class="btn btn-primary btn-comment">
    </a>
    <div class="container">
      {% for comment in post.comments.all%}
          {% if user.is_authenticated or comment.approved_comment %}
              {{ comment.created_date}}
              {% if not comment.approved_comment %}
                  <a class="button btn-default" href="{% url 'comment_remove' pk=comment.pk  %}">
                    <span class="glyphicon glymphicon-remove"></span>
                  </a>
                  <a class="button btn-primary" href="{% url 'comment_approve' pk=comment.pk  %}">
                    <span class="glyphicon glymphicon-remove"></span>
                  </a>
              {% endif %}
              <p>{{ comment.text|safe|linebreaks }}</p>
              <p>Posted By : {{comment.author}} </p>
          {% endif %}
          {% empty %}
          <p> Nom Comments!</p>

      {% endfor %}
    </div>


{% endblock%}

zblog_project/mysite/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html"%}

{% block content %}
  {% for post in post_list %}
    <div class="post">
      <div class="date">
          create: {{post.created_date|date:"D M Y"}}
          <h1><a href="{% url 'post_detail' pk=post.pk %}">{{post.title}}</a></h1>
          <p>{{post.text|truncatechars:200}}</p>
      </div>
    </div>
  {% endfor %}
{% endblock%}

zblog_project/mysite/blog/templates/blog/post_form.html
 {% extends "blog/base.html"%}

{% block content %}
  <h1>New Post</h1>
  <form class="post-form" action="" method="POST">
      {% csrf_token%}
      {{form.as_p}}
    <button type="submit" class="save btn btn-default" name="button">Save</button>

  </form>

  <script >
    var editor = new MediumEditor('.editable');
  </script>
{% endblock%}

zblog_project/mysite/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="centerstage">
    {% for post in post_list %}
      <div class="post">
        <h1><a href="{% url 'post_detail' pk=post.pk %}">{{post.title}}</a></h1>
        <div class="date">
            <p>Publish on :{{post.published|date:"D M Y"}}</p>
        </div>
        <a href="{ % url 'post_detail' pk=post.pk % }">Comments: {{post.approve_comments.count}}</a>
      </div>
    {% endfor %}

  </div>
{% endblock %}